### ISSUE TITLE
PA Review: Creating Routes

### ISSUE THREAD

**Issue by azuzunaga** [azuzunaga/lucha#2]
- [x] Users can create routes with multiple waypoints
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature
- [x] Route display page
- [x] Switch between cycling and running activities in route display page

**Comment by AAlfarho** [comment]
Amazing job on the creation of the routes, the customized map nav bar gives the site a more personal feeling. The current seeding showcases the features of the routes, kudos for both cycling and running tabs!

Google map integration with your app feels consistent and without hiccups. The flow for creating a route feels natural, kudos for that.

There are a couple of minor details we need to address before closing this MVP.

- [x] When Using the map's search functionality, we are forced to click on the _magnifying glass_ icon to move the map to the desired location. Usually, we can also do this by hitting `enter`, however in this case hitting enter triggers a re-render of the page, this is most likely due to a missing `event.preventDefault()` on the form that handles the search.
- [x] (Optional) Regarding the search, when zero results are found let's find a more elegant way of letting the user know, rather an alert.

Feel free to mark the checkboxes yourself after addressing them. Assign this issue back to me once the updates are live in Heroku.

**Comment by azuzunaga** [comment]
Should be all set!

**Comment by AAlfarho** [comment]
Great job on the search bar, the animation lets the user know that something went wrong with their search.

The feature is ready,  kudos!
